In [1]:
from pathlib import Path
import numpy as np
import gym
import sys
sys.path.append('/Users/nakagawaayato/git/2048_RL/env/env0001/')
import gym_2048

In [2]:
env = gym.make('2048-v0')

[2, 2]
[(1, 3), (3, 0)]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]


ValueError: shape mismatch: value array of shape (2,) could not be broadcast to indexing result of shape (2,2,4)

In [7]:
a = np.zeros((4, 4)).astype(np.uint8)

In [12]:
a[(1, 3)]

0